name: libyaml
default_version: "0.2.5"
license: MIT
license_file: License

# Tarball extracts to yaml-VERSION, not libyaml-VERSION.
source:
  url: "https://pyyaml.org/download/libyaml/yaml-0.2.5.tar.gz"
  sha256: "c642ae9b75fee120b2d96c712538bd2cf283228d2337df2cf2988e3c02678ef4"

relative_path: "yaml-0.2.5"

build:
  - configure: []
  - make: []
  - make:
      - install
