name: openssl
default_version: "3.3.1"
license: OpenSSL
license_file: LICENSE

dependencies:
  - zlib

source:
  url: "https://www.openssl.org/source/openssl-3.3.1.tar.gz"
  sha256: "777cd596284c883375a2a7a11bf5d2786fc5413255efab20c50d6ffe6d020b7e"

relative_path: "openssl-3.3.1"

versions:
  - version: "3.3.0"
    source:
      url: "https://www.openssl.org/source/openssl-3.3.0.tar.gz"
      sha256: "53e66b043322a606abf0087e7699a0e033a37fa13feb9742df35c3a33b18fb02"
    relative_path: "openssl-3.3.0"
  - version: "3.2.4"
    source:
      url: "https://www.openssl.org/source/openssl-3.2.4.tar.gz"
      sha256: "b23ad7fd9f73e43ad1767e636040e88ba7c9e5775bfa5618436a0dd2c17c3716"
    relative_path: "openssl-3.2.4"
  - version: "3.0.15"
    source:
      url: "https://www.openssl.org/source/openssl-3.0.15.tar.gz"
      sha256: "23c666d0edf20f14249b3d8f0368acaee9ab585b09e1de82107c66e1f3ec9533"
    relative_path: "openssl-3.0.15"

build:
  - command: "./Configure --prefix=${install_dir} --openssldir=${install_dir}/etc/ssl shared zlib --with-zlib-include=${install_dir}/include --with-zlib-lib=${install_dir}/lib"
  - make: []
  - make:
      - install
